### Download and install pytorch
    Commands from pytorch website

In [ ]:
!pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp35-cp35m-linux_x86_64.whl
!pip install torchvision

In [2]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(123)

### Creating tensors in torch

In [3]:
v = [1, 2, 3]
print(type(v))

v_tensor = torch.Tensor(v)
print(v_tensor)

m2x3 = [[1, 2, 3], [4, 5, 6]]
m2x3_tensor = torch.Tensor(m2x3)
print(type(m2x3))
print(m2x3_tensor)

<class 'list'>
tensor([1., 2., 3.])
<class 'list'>
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Computation graph and automatic differentiation

In [4]:
X = autograd.Variable(torch.Tensor([1, 2, 3]), requires_grad=True)

y = autograd.Variable(torch.Tensor([4, 5, 6]), requires_grad=True)

z = X + y
print(z.data)

operation = z.grad_fn
print(operation)

tensor([5., 7., 9.])


In [5]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


### Gradient
    pytorch can give gradient at any point in time.
    gradient are accumulated if called backward multiple times.

In [6]:
s.backward(retain_graph=True)

In [7]:
print(X)
print(X.grad)
print(y.grad)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 1., 1.])
tensor([1., 1., 1.])


### CUDA

In [8]:
if torch.cuda.is_available():
    
    a = torch.LongTensor(10).fill_(3).cuda()
    print(type(a))
    b = a.cpu()

# Linear Model in Pytorch

In [9]:
import numpy as np

### Create data using numpy

In [11]:
x = [i for i in range(20)]
x_train = np.array(x, dtype=np.float32)
x_train = x_train.reshape(-1, 1)
print(x)
print(x_train.shape)

y = [(5*i + 2) for i in x]
y_train = np.array(y, dtype=np.float32)
y_train = y_train.reshape(-1, 1)
print(y)
print(y_train.shape)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
(20, 1)
[2, 7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97]
(20, 1)


### Create Model class

In [19]:
class LinearRegressor(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegressor, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        out = self.linear(x)
        return out
    
input_dim = 1
output_dim = 1

model = LinearRegressor(input_dim, output_dim)
model

LinearRegressor(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

### Loss and Optimizer

In [21]:
loss_funtion = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.001
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [30]:
epoch = 5000
for epoch in range(epoch):
    epoch += 1
    
    inputs = autograd.Variable(torch.from_numpy(x_train))
    real_outputs = autograd.Variable(torch.from_numpy(y_train))
    
    optimizer.zero_grad()
    
    pred_outputs = model(inputs)
    
    loss = loss_funtion(pred_outputs, real_outputs)
    
    #Compute gradients
    loss.backward()
    
    optimizer.step()
    
    print("epoch: {} loss: {} ".format(epoch, loss.item()))
    

epoch: 1 loss: 0.8618574142456055 
epoch: 2 loss: 0.8609336614608765 
epoch: 3 loss: 0.8600130677223206 
epoch: 4 loss: 0.8590913414955139 
epoch: 5 loss: 0.8581714630126953 
epoch: 6 loss: 0.8572548627853394 
epoch: 7 loss: 0.8563371300697327 
epoch: 8 loss: 0.8554194569587708 
epoch: 9 loss: 0.8545042276382446 
epoch: 10 loss: 0.853589653968811 
epoch: 11 loss: 0.8526764512062073 
epoch: 12 loss: 0.851764440536499 
epoch: 13 loss: 0.8508528470993042 
epoch: 14 loss: 0.8499407768249512 
epoch: 15 loss: 0.8490310311317444 
epoch: 16 loss: 0.8481214046478271 
epoch: 17 loss: 0.8472148776054382 
epoch: 18 loss: 0.846307098865509 
epoch: 19 loss: 0.8454024791717529 
epoch: 20 loss: 0.8444971442222595 
epoch: 21 loss: 0.8435927033424377 
epoch: 22 loss: 0.8426916003227234 
epoch: 23 loss: 0.8417889475822449 
epoch: 24 loss: 0.8408879637718201 
epoch: 25 loss: 0.8399880528450012 
epoch: 26 loss: 0.8390898704528809 
epoch: 27 loss: 0.8381924629211426 
epoch: 28 loss: 0.8372926115989685 
epoc